module.exports = {
    // Announcements: require('./announcement'),
    // Auctions: require('./auction'),
    // Audits: require('./audit'),
    // AuditAucSells: require('./auditaucsell'),
    // AuditTags: require('./audittag'),
    // CardInfo: require('./cardinfo'),
    // Claims: require('./claim'),
    // Guilds: require('./guild'),
    // GuildBuilding: require('./guildbuilding'),
    // GuildUser: require('./guilduser'),
    // Heroes: require('./hero'),
    // Kofis: require('./kofi'),
    // Plots: require('./plot'),
    // Promos: require('./promo'),
    // Tags: require('./tag'),
    // Transactions: require('./transaction'),
    Users: require('./user'),
    // UserCards: require('./usercard'),
    // UserEffects: require('./usereffect'),
    // UserInventory: require('./userinventory'),
    // UserQuests: require('./userquest'),
    // UserSlots: require('./userslot'),
    // UserStats: require('./userstats'),
}