const {model, Schema} = require('mongoose')

const schema = new Schema({
    userID:             { type: String, index: true },
    username:           { type: String },
    daily:              { type: Date },
    claims:             { type: Number, default: 0 },
    promoClaims:        { type: Number, default: 0 },
    totalRegularClaims: { type: Number, default: 0 },
    auctionSell:        { type: Number, default: 0 },
    auctionBid:         { type: Number, default: 0 },
    auctionWin:         { type: Number, default: 0 },
    liquefy:            { type: Number, default: 0 },
    liquefy1:           { type: Number, default: 0 },
    liquefy2:           { type: Number, default: 0 },
    liquefy3:           { type: Number, default: 0 },
    draw:               { type: Number, default: 0 },
    draw1:              { type: Number, default: 0 },
    draw2:              { type: Number, default: 0 },
    draw3:              { type: Number, default: 0 },
    forge:              { type: Number, default: 0 },
    forge1:             { type: Number, default: 0 },
    forge2:             { type: Number, default: 0 },
    forge3:             { type: Number, default: 0 },
    tagsCreated:        { type: Number, default: 0 },
    cardsRated:         { type: Number, default: 0 },
    wish:               { type: Number, default: 0 },
    userSales:          { type: Number, default: 0 },
    botSales:           { type: Number, default: 0 },
    userPurchases:      { type: Number, default: 0 },
    tomatoesIn:         { type: Number, default: 0 },
    tomatoesOut:        { type: Number, default: 0 },
    promoIn:            { type: Number, default: 0 },
    promoOut:           { type: Number, default: 0 },
    vialsIn:            { type: Number, default: 0 },
    vialsOut:           { type: Number, default: 0 },
    lemonsIn:           { type: Number, default: 0 },
    lemonsOut:          { type: Number, default: 0 },
    store:              { type: Number, default: 0 },
    store1:             { type: Number, default: 0 },
    store2:             { type: Number, default: 0 },
    store3:             { type: Number, default: 0 },
    store4:             { type: Number, default: 0 },
    t1quests:           { type: Number, default: 0 },
    t2quests:           { type: Number, default: 0 },
    t3quests:           { type: Number, default: 0 },
    t4quests:           { type: Number, default: 0 },
    t5quests:           { type: Number, default: 0 },
    t6quests:           { type: Number, default: 0 },
})
module.exports = model('Userstats', schema)