module.exports = {
    auction: require('./auction'),
    audit: require('./audit'),
    card: require('./card'),
    checks: require('./checks'),
    collection: require('./collection'),
    commandhandler: require('./commandhandler'),
    effect: require('./effect'),
    eval: require('./eval'),
    guild: require('./guild'),
    hero: require('./hero'),
    interactions: require('./interactions'),
    item: require('./item'),
    messages: require('./messages'),
    meta: require('./meta'),
    modals: require('./modals'),
    plot: require('./plot'),
    preferences: require('./preferences'),
    tag: require('./tag'),
    transaction: require('./transaction'),
    user: require('./transaction'),
    userstats: require('./userstats'),
    webhooks: require('./webhooks'),
    wishlist: require('./wishlist')
}