/* command registry */
require('./admin.js')
require('./auction.js')
require('./audit.js')
require('./card.js')
require('./collection.js')
require('./guild.js')
require('./hero.js')
require('./leaderboards.js')
require('./meta.js')
require('./misc.js')
require('./mod.js')
require('./plot.js')
require('./preferences.js')
require('./smith.js')
require('./store.js')
require('./tag.js')
require('./transaction.js')
require('./user.js')

module.exports = {}