/* command registry */
require('./admin.js')
require('./auction.js')
require('./audit.js')
require('./boost.js')
require('./card.js')
require('./claim.js')
require('./collection.js')
require('./eval.js')
require('./favorite.js')
require('./guild.js')
require('./hero.js')
require('./leaderboards.js')
require('./lock.js')
require('./meta.js')
require('./misc.js')
require('./mod.js')
require('./plot.js')
require('./preferences.js')
require('./rate.js')
require('./smith.js')
require('./store.js')
require('./tag.js')
require('./transaction.js')
require('./user.js')
require('./wishlist')

module.exports = {}