module.exports = {
    Announcements: require('./announcement'),
    Auctions: require('./auction'),
    Audits: require('./audit'),
    AuditAucSells: require('./auditAucSell'),
    AuditTags: require('./auditTag'),
    Cards: require('./card'),
    Claims: require('./claim'),
    Collections: require('./collection'),
    Guilds: require('./guild'),
    GuildBuildings: require('./guildBuilding'),
    GuildUsers: require('./guildUser'),
    Heroes: require('./hero'),
    Plots: require('./plot'),
    Promos: require('./promo'),
    Supports: require('./support'),
    Tags: require('./tag'),
    Transactions: require('./transaction'),
    Users: require('./user'),
    UserCards: require('./userCard'),
    UserEffects: require('./userEffect'),
    UserInventories: require('./userInventory'),
    UserQuests: require('./userQuest'),
    UserSlots: require('./userSlot'),
    UserStats: require('./userStats'),
    UserWishlists: require('./userWishlist'),
}