const {model, Schema} = require('mongoose')

const schema = new Schema({
    userID:             { type: String, index: true },
    daily:              { type: Date, index: true },
    claims:             { type: Number, default: 0 },
    promoclaims:        { type: Number, default: 0 },
    totalRegularClaims: { type: Number, default: 0 },
    aucSell:            { type: Number, default: 0 },
    aucBid:             { type: Number, default: 0 },
    aucWin:             { type: Number, default: 0 },
    liquefy:            { type: Number, default: 0 },
    liquefy1:           { type: Number, default: 0 },
    liquefy2:           { type: Number, default: 0 },
    liquefy3:           { type: Number, default: 0 },
    draw:               { type: Number, default: 0 },
    draw1:              { type: Number, default: 0 },
    draw2:              { type: Number, default: 0 },
    draw3:              { type: Number, default: 0 },
    forge:              { type: Number, default: 0 },
    forge1:             { type: Number, default: 0 },
    forge2:             { type: Number, default: 0 },
    forge3:             { type: Number, default: 0 },
    tags:               { type: Number, default: 0 },
    rates:              { type: Number, default: 0 },
    wish:               { type: Number, default: 0 },
    userSell:           { type: Number, default: 0 },
    botSell:            { type: Number, default: 0 },
    userBuy:            { type: Number, default: 0 },
    tomatoIn:           { type: Number, default: 0 },
    tomatoOut:          { type: Number, default: 0 },
    promoIn:            { type: Number, default: 0 },
    promoOut:           { type: Number, default: 0 },
    vialIn:             { type: Number, default: 0 },
    vialOut:            { type: Number, default: 0 },
    lemonIn:            { type: Number, default: 0 },
    lemonOut:           { type: Number, default: 0 },
    store:              { type: Number, default: 0 },
    storePlot:          { type: Number, default: 0 },
    storeRecipe:        { type: Number, default: 0 },
    storeTicket:        { type: Number, default: 0 },
    storeBonus:         { type: Number, default: 0 },
    t1Quests:           { type: Number, default: 0 },
    t2Quests:           { type: Number, default: 0 },
    t3Quests:           { type: Number, default: 0 },
    t4Quests:           { type: Number, default: 0 },
    t5Quests:           { type: Number, default: 0 },
    t6Quests:           { type: Number, default: 0 },
})
module.exports = model('UserStat', schema)